---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    hystrix.enabled: "true"
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "${project.version}"
    group: "io.fabric8.kubeflix"
  name: "hello-ribbon"
spec:
  replicas: 1
  selector:
    matchLabels:
      hystrix.enabled: "true"
      project: "${project.artifactId}"
      provider: "fabric8"
      group: "io.fabric8.kubeflix"
  template:
    metadata:
      labels:
        hystrix.enabled: "true"
        project: "${project.artifactId}"
        provider: "fabric8"
        version: "${project.version}"
        group: "io.fabric8.kubeflix"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/hello-ribbon:${project.version}"
        name: "hello-ribbon"
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 8778
          name: "jolokia"
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 8080
          initialDelaySeconds: 5
      serviceAccountName: "ribbon"
